import dynamic from 'next/dynamic';
import React from 'react';
import Head from 'next/head';
import Layout from 'components/Layout';

const LocationContainer = dynamic(() => import('containers/Location'), { ssr: false });

const Page = () => {
    return (
        <div>
            <Head>
                <title>Location Admin</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Layout>
                <LocationContainer />
            </Layout>
        </div>
    );
};

export default Page;
