import React from 'react';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Layout from 'components/Layout';

const EditTournament = dynamic(() => import('containers/EditTournament'));

const Page = () => {
    return (
        <div>
            <Head>
                <title>Edit Tournament</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Layout>
                <EditTournament />
            </Layout>
        </div>
    );
};

export default Page;
