import dynamic from 'next/dynamic';
import React from 'react';
import Head from 'next/head';
import Layout from 'components/Layout';

const ClientAccountContainer = dynamic(() => import('container/ClientAccount'), { ssr: false });

const Page = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Layout>
                <ClientAccountContainer />
            </Layout>
        </div>
    );
};

export default Page;
