import dynamic from 'next/dynamic';
import React from 'react';
import Head from 'next/head';
import Layout from 'components/Layout';

const EditAccountContainer = dynamic(() => import('containers/EditAccount'), { ssr: false });

const Page = () => {
    return (
        <div>
            <Head>
                <title>Edit Account | Prizeplay Admin</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Layout>
                <EditAccountContainer />
            </Layout>
        </div>
    );
};

Page.getPageProps = async () => {
    return {
        protectedRoute: true
    };
};

export default Page;
