const dummy = [
    {
        id: 1,
        title: 'Open Tourney Pre Launch Hop up',
        start: new Date(),
        end: new Date(),
        isActive: true,
        games: 'Hop Up',
        registration: 20,
        totalPrizes: 30000,
        leaderboard: [
            { rank: 1, avatar: '/images/ava-tour-admin.png', username: 'owi1-kun', scores: 300000, points: 1000 },
            { rank: 2, avatar: '/images/ava-tour-admin.png', username: 'okoj-kun', scores: 200000, points: 500 },
            { rank: 3, avatar: '/images/ava-tour-admin.png', username: 'mina-chan', scores: 150000, points: 250 },
            { rank: 4, avatar: '/images/ava-tour-admin.png', username: 'obmas-kun', scores: 100000, points: 500 },
            { rank: 5, avatar: '/images/ava-tour-admin.png', username: 'nobita-kun', scores: 200000, points: 500 },
            { rank: 6, avatar: '/images/ava-tour-admin.png', username: 'saitamu-kun', scores: 200000, points: 500 },
            { rank: 7, avatar: '/images/ava-tour-admin.png', username: 'narto-kun', scores: 200000, points: 500 },
            { rank: 8, avatar: '/images/ava-tour-admin.png', username: 'sakora-san', scores: 200000, points: 500 },
            { rank: 9, avatar: '/images/ava-tour-admin.png', username: 'hinasaja-chan', scores: 200000, points: 500 },
            { rank: 10, avatar: '/images/ava-tour-admin.png', username: 'screen-kun', scores: 200000, points: 500 },
            { rank: 11, avatar: '/images/ava-tour-admin.png', username: 'moni-kun', scores: 200000, points: 500 },
            { rank: 12, avatar: '/images/ava-tour-admin.png', username: 'thor-kun', scores: 200000, points: 500 }
        ]
    },
    {
        id: 2,
        title: 'Open Tourney Pre Launch Hop up',
        start: new Date(),
        end: new Date(),
        isActive: false,
        games: 'Tower Stack',
        registration: 20,
        totalPrizes: 30000,
        leaderboard: [
            { rank: 1, avatar: '/images/ava-tour-admin.png', username: 'owi2-kun', scores: 300000, points: 1000 },
            { rank: 2, avatar: '/images/ava-tour-admin.png', username: 'okoj-kun', scores: 200000, points: 500 },
            { rank: 3, avatar: '/images/ava-tour-admin.png', username: 'mina-chan', scores: 150000, points: 250 },
            { rank: 4, avatar: '/images/ava-tour-admin.png', username: 'obmas-kun', scores: 100000, points: 500 },
            { rank: 5, avatar: '/images/ava-tour-admin.png', username: 'nobita-kun', scores: 200000, points: 500 },
            { rank: 6, avatar: '/images/ava-tour-admin.png', username: 'saitamu-kun', scores: 200000, points: 500 },
            { rank: 7, avatar: '/images/ava-tour-admin.png', username: 'narto-kun', scores: 200000, points: 500 },
            { rank: 8, avatar: '/images/ava-tour-admin.png', username: 'sakora-san', scores: 200000, points: 500 },
            { rank: 9, avatar: '/images/ava-tour-admin.png', username: 'hinasaja-chan', scores: 200000, points: 500 },
            { rank: 10, avatar: '/images/ava-tour-admin.png', username: 'screen-kun', scores: 200000, points: 500 },
            { rank: 11, avatar: '/images/ava-tour-admin.png', username: 'moni-kun', scores: 200000, points: 500 },
            { rank: 12, avatar: '/images/ava-tour-admin.png', username: 'thor-kun', scores: 200000, points: 500 }
        ]
    },
    {
        id: 3,
        title: 'Open Tourney Pre Launch Hop up',
        start: new Date(),
        end: new Date(),
        isActive: true,
        games: 'Rose Dart',
        registration: 20,
        totalPrizes: 30000,
        leaderboard: [
            { rank: 1, avatar: '/images/ava-tour-admin.png', username: 'owi3-kun', scores: 300000, points: 1000 },
            { rank: 2, avatar: '/images/ava-tour-admin.png', username: 'okoj-kun', scores: 200000, points: 500 },
            { rank: 3, avatar: '/images/ava-tour-admin.png', username: 'mina-chan', scores: 150000, points: 250 },
            { rank: 4, avatar: '/images/ava-tour-admin.png', username: 'obmas-kun', scores: 100000, points: 500 },
            { rank: 5, avatar: '/images/ava-tour-admin.png', username: 'nobita-kun', scores: 200000, points: 500 },
            { rank: 6, avatar: '/images/ava-tour-admin.png', username: 'saitamu-kun', scores: 200000, points: 500 },
            { rank: 7, avatar: '/images/ava-tour-admin.png', username: 'narto-kun', scores: 200000, points: 500 },
            { rank: 8, avatar: '/images/ava-tour-admin.png', username: 'sakora-san', scores: 200000, points: 500 },
            { rank: 9, avatar: '/images/ava-tour-admin.png', username: 'hinasaja-chan', scores: 200000, points: 500 },
            { rank: 10, avatar: '/images/ava-tour-admin.png', username: 'screen-kun', scores: 200000, points: 500 },
            { rank: 11, avatar: '/images/ava-tour-admin.png', username: 'moni-kun', scores: 200000, points: 500 },
            { rank: 12, avatar: '/images/ava-tour-admin.png', username: 'thor-kun', scores: 200000, points: 500 }
        ]
    },
    {
        id: 4,
        title: 'Open Tourney Pre Launch Hop up',
        start: new Date(),
        end: new Date(),
        isActive: false,
        games: 'Mobile Legend',
        registration: 20,
        totalPrizes: 30000,
        leaderboard: [
            { rank: 1, avatar: '/images/ava-tour-admin.png', username: 'owi4-kun', scores: 300000, points: 1000 },
            { rank: 2, avatar: '/images/ava-tour-admin.png', username: 'okoj-kun', scores: 200000, points: 500 },
            { rank: 3, avatar: '/images/ava-tour-admin.png', username: 'mina-chan', scores: 150000, points: 250 },
            { rank: 4, avatar: '/images/ava-tour-admin.png', username: 'obmas-kun', scores: 100000, points: 500 },
            { rank: 5, avatar: '/images/ava-tour-admin.png', username: 'nobita-kun', scores: 200000, points: 500 },
            { rank: 6, avatar: '/images/ava-tour-admin.png', username: 'saitamu-kun', scores: 200000, points: 500 },
            { rank: 7, avatar: '/images/ava-tour-admin.png', username: 'narto-kun', scores: 200000, points: 500 },
            { rank: 8, avatar: '/images/ava-tour-admin.png', username: 'sakora-san', scores: 200000, points: 500 },
            { rank: 9, avatar: '/images/ava-tour-admin.png', username: 'hinasaja-chan', scores: 200000, points: 500 },
            { rank: 10, avatar: '/images/ava-tour-admin.png', username: 'screen-kun', scores: 200000, points: 500 },
            { rank: 11, avatar: '/images/ava-tour-admin.png', username: 'moni-kun', scores: 200000, points: 500 },
            { rank: 12, avatar: '/images/ava-tour-admin.png', username: 'thor-kun', scores: 200000, points: 500 }
        ]
    },
    {
        id: 5,
        title: 'Open Tourney Pre Launch Hop up',
        start: new Date(),
        end: new Date(),
        isActive: false,
        games: 'Evermore Knight',
        registration: 20,
        totalPrizes: 30000,
        leaderboard: [
            { rank: 1, avatar: '/images/ava-tour-admin.png', username: 'owi5-kun', scores: 300000, points: 1000 },
            { rank: 2, avatar: '/images/ava-tour-admin.png', username: 'okoj-kun', scores: 200000, points: 500 },
            { rank: 3, avatar: '/images/ava-tour-admin.png', username: 'mina-chan', scores: 150000, points: 250 },
            { rank: 4, avatar: '/images/ava-tour-admin.png', username: 'obmas-kun', scores: 100000, points: 500 },
            { rank: 5, avatar: '/images/ava-tour-admin.png', username: 'nobita-kun', scores: 200000, points: 500 },
            { rank: 6, avatar: '/images/ava-tour-admin.png', username: 'saitamu-kun', scores: 200000, points: 500 },
            { rank: 7, avatar: '/images/ava-tour-admin.png', username: 'narto-kun', scores: 200000, points: 500 },
            { rank: 8, avatar: '/images/ava-tour-admin.png', username: 'sakora-san', scores: 200000, points: 500 },
            { rank: 9, avatar: '/images/ava-tour-admin.png', username: 'hinasaja-chan', scores: 200000, points: 500 },
            { rank: 10, avatar: '/images/ava-tour-admin.png', username: 'screen-kun', scores: 200000, points: 500 },
            { rank: 11, avatar: '/images/ava-tour-admin.png', username: 'moni-kun', scores: 200000, points: 500 },
            { rank: 12, avatar: '/images/ava-tour-admin.png', username: 'thor-kun', scores: 200000, points: 500 }
        ]
    },
    {
        id: 6,
        title: 'Open Tourney Pre Launch Hop up',
        start: new Date(),
        end: new Date(),
        isActive: true,
        games: 'Slime Haven',
        registration: 20,
        totalPrizes: 30000,
        leaderboard: [
            { rank: 1, avatar: '/images/ava-tour-admin.png', username: 'owi6-kun', scores: 300000, points: 1000 },
            { rank: 2, avatar: '/images/ava-tour-admin.png', username: 'okoj-kun', scores: 200000, points: 500 },
            { rank: 3, avatar: '/images/ava-tour-admin.png', username: 'mina-chan', scores: 150000, points: 250 },
            { rank: 4, avatar: '/images/ava-tour-admin.png', username: 'obmas-kun', scores: 100000, points: 500 },
            { rank: 5, avatar: '/images/ava-tour-admin.png', username: 'nobita-kun', scores: 200000, points: 500 },
            { rank: 6, avatar: '/images/ava-tour-admin.png', username: 'saitamu-kun', scores: 200000, points: 500 },
            { rank: 7, avatar: '/images/ava-tour-admin.png', username: 'narto-kun', scores: 200000, points: 500 },
            { rank: 8, avatar: '/images/ava-tour-admin.png', username: 'sakora-san', scores: 200000, points: 500 },
            { rank: 9, avatar: '/images/ava-tour-admin.png', username: 'hinasaja-chan', scores: 200000, points: 500 },
            { rank: 10, avatar: '/images/ava-tour-admin.png', username: 'screen-kun', scores: 200000, points: 500 },
            { rank: 11, avatar: '/images/ava-tour-admin.png', username: 'moni-kun', scores: 200000, points: 500 },
            { rank: 12, avatar: '/images/ava-tour-admin.png', username: 'thor-kun', scores: 200000, points: 500 }
        ]
    },
    {
        id: 7,
        title: 'Open Tourney Pre Launch Hop up',
        start: new Date(),
        end: new Date(),
        isActive: true,
        games: 'Harvestmoon',
        registration: 20,
        totalPrizes: 30000,
        leaderboard: [
            { rank: 1, avatar: '/images/ava-tour-admin.png', username: 'owi7-kun', scores: 300000, points: 1000 },
            { rank: 2, avatar: '/images/ava-tour-admin.png', username: 'okoj-kun', scores: 200000, points: 500 },
            { rank: 3, avatar: '/images/ava-tour-admin.png', username: 'mina-chan', scores: 150000, points: 250 },
            { rank: 4, avatar: '/images/ava-tour-admin.png', username: 'obmas-kun', scores: 100000, points: 500 },
            { rank: 5, avatar: '/images/ava-tour-admin.png', username: 'nobita-kun', scores: 200000, points: 500 },
            { rank: 6, avatar: '/images/ava-tour-admin.png', username: 'saitamu-kun', scores: 200000, points: 500 },
            { rank: 7, avatar: '/images/ava-tour-admin.png', username: 'narto-kun', scores: 200000, points: 500 },
            { rank: 8, avatar: '/images/ava-tour-admin.png', username: 'sakora-san', scores: 200000, points: 500 },
            { rank: 9, avatar: '/images/ava-tour-admin.png', username: 'hinasaja-chan', scores: 200000, points: 500 },
            { rank: 10, avatar: '/images/ava-tour-admin.png', username: 'screen-kun', scores: 200000, points: 500 },
            { rank: 11, avatar: '/images/ava-tour-admin.png', username: 'moni-kun', scores: 200000, points: 500 },
            { rank: 12, avatar: '/images/ava-tour-admin.png', username: 'thor-kun', scores: 200000, points: 500 }
        ]
    },
    {
        id: 8,
        title: 'Open Tourney Pre Launch Hop up',
        start: new Date(),
        end: new Date(),
        isActive: false,
        games: 'Barbar Q',
        registration: 20,
        totalPrizes: 30000,
        leaderboard: [
            { rank: 1, avatar: '/images/ava-tour-admin.png', username: 'owi8-kun', scores: 300000, points: 1000 },
            { rank: 2, avatar: '/images/ava-tour-admin.png', username: 'okoj-kun', scores: 200000, points: 500 },
            { rank: 3, avatar: '/images/ava-tour-admin.png', username: 'mina-chan', scores: 150000, points: 250 },
            { rank: 4, avatar: '/images/ava-tour-admin.png', username: 'obmas-kun', scores: 100000, points: 500 },
            { rank: 5, avatar: '/images/ava-tour-admin.png', username: 'nobita-kun', scores: 200000, points: 500 },
            { rank: 6, avatar: '/images/ava-tour-admin.png', username: 'saitamu-kun', scores: 200000, points: 500 },
            { rank: 7, avatar: '/images/ava-tour-admin.png', username: 'narto-kun', scores: 200000, points: 500 },
            { rank: 8, avatar: '/images/ava-tour-admin.png', username: 'sakora-san', scores: 200000, points: 500 },
            { rank: 9, avatar: '/images/ava-tour-admin.png', username: 'hinasaja-chan', scores: 200000, points: 500 },
            { rank: 10, avatar: '/images/ava-tour-admin.png', username: 'screen-kun', scores: 200000, points: 500 },
            { rank: 11, avatar: '/images/ava-tour-admin.png', username: 'moni-kun', scores: 200000, points: 500 },
            { rank: 12, avatar: '/images/ava-tour-admin.png', username: 'thor-kun', scores: 200000, points: 500 }
        ]
    },
    {
        id: 9,
        title: 'Open Tourney Pre Launch Hop up',
        start: new Date(),
        end: new Date(),
        isActive: true,
        games: 'Hay Day',
        registration: 20,
        totalPrizes: 30000,
        leaderboard: [
            { rank: 1, avatar: '/images/ava-tour-admin.png', username: 'owi9-kun', scores: 300000, points: 1000 },
            { rank: 2, avatar: '/images/ava-tour-admin.png', username: 'okoj-kun', scores: 200000, points: 500 },
            { rank: 3, avatar: '/images/ava-tour-admin.png', username: 'mina-chan', scores: 150000, points: 250 },
            { rank: 4, avatar: '/images/ava-tour-admin.png', username: 'obmas-kun', scores: 100000, points: 500 },
            { rank: 5, avatar: '/images/ava-tour-admin.png', username: 'nobita-kun', scores: 200000, points: 500 },
            { rank: 6, avatar: '/images/ava-tour-admin.png', username: 'saitamu-kun', scores: 200000, points: 500 },
            { rank: 7, avatar: '/images/ava-tour-admin.png', username: 'narto-kun', scores: 200000, points: 500 },
            { rank: 8, avatar: '/images/ava-tour-admin.png', username: 'sakora-san', scores: 200000, points: 500 },
            { rank: 9, avatar: '/images/ava-tour-admin.png', username: 'hinasaja-chan', scores: 200000, points: 500 },
            { rank: 10, avatar: '/images/ava-tour-admin.png', username: 'screen-kun', scores: 200000, points: 500 },
            { rank: 11, avatar: '/images/ava-tour-admin.png', username: 'moni-kun', scores: 200000, points: 500 },
            { rank: 12, avatar: '/images/ava-tour-admin.png', username: 'thor-kun', scores: 200000, points: 500 }
        ]
    },
    {
        id: 10,
        title: 'Open Tourney Pre Launch Hop up',
        start: new Date(),
        end: new Date(),
        isActive: false,
        games: 'Dragonest',
        registration: 20,
        totalPrizes: 30000,
        leaderboard: [
            { rank: 1, avatar: '/images/ava-tour-admin.png', username: 'owi10-kun', scores: 300000, points: 1000 },
            { rank: 2, avatar: '/images/ava-tour-admin.png', username: 'okoj-kun', scores: 200000, points: 500 },
            { rank: 3, avatar: '/images/ava-tour-admin.png', username: 'mina-chan', scores: 150000, points: 250 },
            { rank: 4, avatar: '/images/ava-tour-admin.png', username: 'obmas-kun', scores: 100000, points: 500 },
            { rank: 5, avatar: '/images/ava-tour-admin.png', username: 'nobita-kun', scores: 200000, points: 500 },
            { rank: 6, avatar: '/images/ava-tour-admin.png', username: 'saitamu-kun', scores: 200000, points: 500 },
            { rank: 7, avatar: '/images/ava-tour-admin.png', username: 'narto-kun', scores: 200000, points: 500 },
            { rank: 8, avatar: '/images/ava-tour-admin.png', username: 'sakora-san', scores: 200000, points: 500 },
            { rank: 9, avatar: '/images/ava-tour-admin.png', username: 'hinasaja-chan', scores: 200000, points: 500 },
            { rank: 10, avatar: '/images/ava-tour-admin.png', username: 'screen-kun', scores: 200000, points: 500 },
            { rank: 11, avatar: '/images/ava-tour-admin.png', username: 'moni-kun', scores: 200000, points: 500 },
            { rank: 12, avatar: '/images/ava-tour-admin.png', username: 'thor-kun', scores: 200000, points: 500 }
        ]
    },
    {
        id: 11,
        title: 'Open Tourney Pre Launch Hop up',
        start: new Date(),
        end: new Date(),
        isActive: false,
        games: 'Point Blank',
        registration: 20,
        totalPrizes: 30000,
        leaderboard: [
            { rank: 1, avatar: '/images/ava-tour-admin.png', username: 'owi1-kun', scores: 300000, points: 1000 },
            { rank: 2, avatar: '/images/ava-tour-admin.png', username: 'okoj-kun', scores: 200000, points: 500 },
            { rank: 3, avatar: '/images/ava-tour-admin.png', username: 'mina-chan', scores: 150000, points: 250 },
            { rank: 4, avatar: '/images/ava-tour-admin.png', username: 'obmas-kun', scores: 100000, points: 500 },
            { rank: 5, avatar: '/images/ava-tour-admin.png', username: 'nobita-kun', scores: 200000, points: 500 },
            { rank: 6, avatar: '/images/ava-tour-admin.png', username: 'saitamu-kun', scores: 200000, points: 500 },
            { rank: 7, avatar: '/images/ava-tour-admin.png', username: 'narto-kun', scores: 200000, points: 500 },
            { rank: 8, avatar: '/images/ava-tour-admin.png', username: 'sakora-san', scores: 200000, points: 500 },
            { rank: 9, avatar: '/images/ava-tour-admin.png', username: 'hinasaja-chan', scores: 200000, points: 500 },
            { rank: 10, avatar: '/images/ava-tour-admin.png', username: 'screen-kun', scores: 200000, points: 500 },
            { rank: 11, avatar: '/images/ava-tour-admin.png', username: 'moni-kun', scores: 200000, points: 500 },
            { rank: 12, avatar: '/images/ava-tour-admin.png', username: 'thor-kun', scores: 200000, points: 500 }
        ]
    }
];

export default dummy;
