import { Typography } from '@mui/material';
import Layout from 'components/Layout';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Layout>
                <Typography component='h1' sx={{ color: 'red' }}>
                    Testing
                </Typography>
            </Layout>
        </div>
    );
};

export default Home;
