import Layout from 'components/Layout';
import type { NextPage } from 'next';
import Head from 'next/head';
import dynamic from 'next/dynamic';

const HomeContainer = dynamic(() => import('containers/Home'));

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Prize Play Admin</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Layout>
                <HomeContainer />
            </Layout>
        </div>
    );
};

export default Home;
