import React from 'react';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Layout from 'components/Layout';

const AddSetPrizeContainer = dynamic(() => import('containers/AddSetPrize'), { ssr: false });

const Page = () => {
    return (
        <>
            <Head>
                <title>Add Set Prize | Tournament Admin</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Layout>
                <AddSetPrizeContainer />
            </Layout>
        </>
    );
};

export default Page;
